In [ ]:
import numpy as np

**Creating a Matrix using Numpy**

In [ ]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2 = np.array([[10,35,35],[20,60,80],[10,78,34]])
print(matrix_2)
print(matrix_2.shape)

[[10 35 35]
 [20 60 80]
 [10 78 34]]
(3, 3)


In [ ]:
# creating matrix with random values
random_matrix  = np.random.rand(3,3)
print(random_matrix)

[[0.57928511 0.98287499 0.28696043]
 [0.92324953 0.11603716 0.34565945]
 [0.00748749 0.89882419 0.37974989]]


In [ ]:
# creating matrix with random integers
random_matrix_1 = np.random.randint(100, size=(4,5))
print(random_matrix_1)

[[48  6  4  1 13]
 [17 45 82 58 44]
 [86 59 68 49 64]
 [61 51 19 18 94]]


In [ ]:
# matrix with all the values as 1
matrix_3 = np.ones((6,7), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [ ]:
# null matrix
matrix_4 = np.zeros((4,5), dtype=int)
print(matrix_4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# Identity matrix
matrix_5 = np.eye(3,3,dtype=int)
print(matrix_5)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


**Transpose of a Matrix**

In [ ]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

b = a.transpose()
print(b)

c = np.transpose(a)
print(c)

[[31  3 92 33 46]
 [78  9 62 76 86]
 [91 77  9 97 90]
 [40 59 16 13 81]]
[[31 78 91 40]
 [ 3  9 77 59]
 [92 62  9 16]
 [33 76 97 13]
 [46 86 90 81]]
[[31 78 91 40]
 [ 3  9 77 59]
 [92 62  9 16]
 [33 76 97 13]
 [46 86 90 81]]


**Matrix Addition and Subtraction:**

In [ ]:
# Creating two matrix with same shape

a = np.array([[2,3],[4,5]])
b = np.array([[10,12],[14,16]])

matrix_sum = a+b
print(matrix_sum)

matrix_difference = a-b
print(matrix_difference)

[[12 15]
 [18 21]]
[[ -8  -9]
 [-10 -11]]


In [ ]:
# matrix with random values
matrix_1 = np.random.randint(50, size=(3,4))
matrix_2 = np.random.randint(30, size=(3,4))

matrix_sum = matrix_1 + matrix_2
print(matrix_sum)

matrix_difference = matrix_1 - matrix_2
print(matrix_difference)

[[37 75 15 33]
 [22 40 56 18]
 [70 31 16 30]]
[[ -9  19   5  25]
 [ 16   4   2  -2]
 [ 22 -21  -4  30]]


In [ ]:
sum = np.add(matrix_1, matrix_2)
print(sum)

diff = np.subtract(matrix_1,matrix_2)
print(diff)

[[11 21 63 57]
 [25 47 35 25]
 [30 27 45  5]]
[[  3 -15  21  31]
 [ 21  23  11  -7]
 [ 26  -9  23   5]]


**Multiplying a Matrix by Scaler:**

In [ ]:
x = 5
y = np.random.randint(10, size=(4,5))

print(y)
print(x*y)

[[1 3 1 0 9]
 [9 0 6 7 7]
 [4 5 2 3 6]
 [2 6 8 6 1]]
[[ 5 15  5  0 45]
 [45  0 30 35 35]
 [20 25 10 15 30]
 [10 30 40 30  5]]


**Multiplication of two Matrices**

In [ ]:
matrix_3 = np.random.randint(20, size=(3,4))
matrix_4 = np.random.randint(15, size=(4,3))

product = np.dot(matrix_3,matrix_4)
print(product)

[[313 312 413]
 [234 349 265]
 [292 387 521]]


In [ ]:
# Element wise matrix multiplication
matrix_5 = np.random.randint(50, size=(3,4))
matrix_6 = np.random.randint(30, size=(3,4))

prod = np.multiply(matrix_5,matrix_6)
print(prod)

[[ 684   92 1044  378]
 [ 140  272    3   24]
 [ 168  164  378   81]]
